version: '3.8'
volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file: .env
    container_name: tracker_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: tracker_backend
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    build:
      context: ../tracker-frontend/
      dockerfile: Dockerfile
    container_name: tracker_frontend
    volumes: 
      - static:/frontend_static 

  nginx:
    build: ./infra/
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
      - media:/media